services:

  back-server:
    build:
      context: ./backend
    container_name: iot-backend-server
    depends_on:
      - mqtt-broker
    volumes:
      - ./backend:/app
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883

  iot-frontend:
    build:
      context: ./frontend
    container_name: iot-frontend-react
    ports:
      - "3000:3000"
    depends_on:
      - mqtt-broker
    environment:
      - REACT_APP_MQTT_BROKER_HOST=mqtt-broker
      - REACT_APP_MQTT_BROKER_PORT=1883

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
      - ./broker/config:/mosquitto/config

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - INFLUXD_LOG_LEVEL=info

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123