apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086  # Use the service name for internal Docker networking
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: iot-org
      defaultBucket: iot-bucket
    secureJsonData:
      token: RkJYZSVOrz7UZz65-10ZMio-QOgZAXD8jsbXxEzrqrtbKbnE9FJsi33Yx2-fuQHoT4E7llu4K6znqsKwo_p51w==  # Replace with your actual InfluxDB token
